### ISSUE TITLE
Unknown project's license

### ISSUE THREAD

**Issue by kenliten** [JayeshTiwari03/Dark-Mode-Demo#1]
Hello!

I want to use your code in my own project, a npm package to generate boilerplates for web projects.

Unfortunately, you aren't providing information about licensing, so if you have some terms I would love to know about them.

Thank you!

**Comment by JayeshTiwari03** [comment]
Hi,
Feel free to use this code. I have added a license too. I'll be glad if you could mention me in the credits.
Keep up the good work.

Cheers 🎉

**Comment by kenliten** [comment]
Of course, and thank you!
